version: '3'

services:
  devicedb:
    build:
      context: ./docker/mongodb_replica
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: concreteAI
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27017
    volumes:
      - device_mongodb:/data/db
      - ./docker/mongodb_replica/init:/docker-entrypoint-initdb.d:ro
    networks:
      - app_network
    restart: always

volumes:
  device_mongodb:

networks:
  app_network:
    driver: bridge
